[server]
maxUploadSize = 15
#port=9988

[theme]
# Primary accent for interactive elements
primaryColor = '#a38b31'

# Background color for the main content area
backgroundColor = '#F4F4F5'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFF9E9'

# Color used for almost all text
textColor = '#333333'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

# base="light"
# primaryColor="purple"